services:

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: POSTGRES_DB
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASS
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    environment:
      - GATEWAY_SERVER_PORT
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    restart: always

  registry-service:
    build:
      context: registry-service
      dockerfile: Dockerfile
    container_name: registry-service
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA
      - EUREKA_CLIENT_FETCH_REGISTRY
      - EUREKA_SERVER_ENABLE_SELF_PRESERVATION
      - REGISTRY_SERVER_PORT
    restart: always

  auth-service:
    build:
      context: auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD
      - AUTH_SERVER_PORT
      - EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE
    restart: always


volumes:
  pgdata: