services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - swiftbank-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  registry-service:
    build:
      context: ./swiftbank-core/registry-service
      dockerfile: Dockerfile
    container_name: registry-service
    ports:
      - "8761:8761"
    networks:
      - swiftbank-network
    environment:
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
      EUREKA_CLIENT_FETCH_REGISTRY: ${EUREKA_CLIENT_FETCH_REGISTRY}
      EUREKA_SERVER_ENABLE_SELF_PRESERVATION: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION}
      REGISTRY_SERVER_PORT: ${REGISTRY_SERVER_PORT}
    restart: always

  api-gateway:
    build:
      context: ./swiftbank-core/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    depends_on:
      - registry-service
    networks:
      - swiftbank-network
    ports:
      - "8080:8080"
    environment:
      GATEWAY_SERVER_PORT: ${GATEWAY_SERVER_PORT}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    restart: always

  auth-service:
    build:
      context: ./swiftbank-core/auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - postgres
      - registry-service
    networks:
      - swiftbank-network
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      AUTH_SERVER_PORT: ${AUTH_SERVER_PORT}
      EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE: ${EUREKA_CLIENT_SERVICE_URL_DEFAULT_ZONE}
    restart: always

volumes:
  pgdata:

networks:
  swiftbank-network:
    driver: bridge