spring:
  application:
    name: notification-service

  # RabbitMQ
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3000
          max-attempts: 3

  # Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 60000

  # Email
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${EMAIL_SMTP_AUTH}
          starttls:
            enable: ${EMAIL_SMTP_STARTTLS}
          timeout: 5000
          connection-timeout: 5000

# Notification Settings
notification:
  from: ${EMAIL_FROM}
  reset-password:
    subject: ${RESET_PASSWORD_SUBJECT}
    link-en: ${RESET_PASSWORD_LINK_EN}
    link-ua: ${RESET_PASSWORD_LINK_UA}
    token-ttl-minutes: ${RESET_TOKEN_TTL_MINUTES}

# Server
server:
  port: ${SERVER_PORT}

# Logging
logging:
  level:
    root: INFO
    com.swiftbank.notificationservice: DEBUG